name: block-pr

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [synchronize, reopened, edited]
    branches:
      - develop
      - main

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    if:
      (
      github.event.pull_request.head.ref  != 'develop' &&
      github.event.pull_request.base.ref == 'main'
      ) ||
      (
      github.event.pull_request.head.ref == 'main' &&
      github.event.pull_request.base.ref == 'develop'
      )
    steps:
      - name: Check branch name
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: |
          exit 0
