name: block-pr

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [synchronize, reopened, edited]
    branches:
      - develop
      - main

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: |
          exit 1
