name: block-pr

on:
  pull_request:
    branches:
      - '**'

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "----"
          echo $GITHUB_HEAD_REF
          if [ "$GITHUB_HEAD_REF" != "develop"  ||  "$GITHUB_HEAD_REF" != "main" ]; then
            echo "Pull request not allowed from branch $GITHUB_HEAD_REF. Only pull requests from the develop branch are allowed."
            exit 1
          fi

  protect_branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Protect branch
        uses: peter-evans/protect-branch@v3.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: true
          required_approving_review_count: 1
          required_status_checks: |
            {
              "strict": true,
              "contexts": ["reject_pr_job"]
            }
