name: block-pr

on:
  pull_request:
    branches:
      - '**'

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    steps:      
      - name: Check branch name
        if: github.event.pull_request.base.ref == 'main'
        run: |
          if [ "$GITHUB_HEAD_REF" != "develop"  ||  "$GITHUB_HEAD_REF" != "main" ]; then
            echo "Pull request not allowed from branch $GITHUB_HEAD_REF. Only pull requests from the develop branch are allowed."
            exit 1
          fi

      - name: Set status check
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request-status@v1.1.1
        with:
          token: ${{ secrets.TOKEN_CHANGELOG }}
          state: success
          description: 'PR is allowed to be merged'


