name: Block pull requests to main and run on merge of pull request from develop

on:
  pull_request:
    branches:
      - '**'

jobs:
  block-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: |
          echo "GITHUB_HEAD_REF -- $GITHUB_HEAD_REF"
          echo "---"
      
      - name: Check branch name
        if:  == 'main'
        run: |
          if [ "$GITHUB_HEAD_REF" != "develop" ]; then
            echo "Pull request not allowed from branch $GITHUB_HEAD_REF. Only pull requests from the develop branch are allowed."
            exit 1
          fi
