name: Changelog steps

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  reject_pr_job:
    runs-on: ubuntu-latest
    steps:
      - name: do-nothing
        run: echo "This job does nothing"
      - name: Set status
        uses: actions/github-script@v3
        with:
          script: |
            const { github: gh } = require('@actions/github');
            const octokit = new gh.getOctokit('${{ secrets.TOKEN_CHANGELOG }}');
            const { data: statuses } = await octokit.rest.repos.listStatusesForRef({
              owner: gh.context.repo.owner,
              repo: gh.context.repo.repo,
              ref: gh.context.sha,
            });
            const statusExists = statuses.some(status => status.context === 'reject_pr_job');
            if (!statusExists) {
              await octokit.rest.repos.createCommitStatus({
                owner: gh.context.repo.owner,
                repo: gh.context.repo.repo,
                sha: gh.context.sha,
                state: 'success',
                context: 'reject_pr_job',
                description: 'The reject_pr_job succeeded',
              });
            }


  run-on-merge:
    needs: reject_pr_job
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: run-bash-file
        run: |
          git fetch 
          chmod 777 script.sh
          repository_name="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          should_add_last_changes_to_master=$(./script.sh $repository_name)
          echo $should_add_last_changes_to_master
          echo "should_add_last_changes_to_master=$should_add_last_changes_to_master" >> $GITHUB_ENV

      - name: commit-push-changes
        uses: actions-js/push@master
        if: ${{env.should_add_last_changes_to_master == 'true'}}
        with:
          github_token: ${{ secrets.TOKEN_CHANGELOG }}
          message: "Changelog version updated"
          tags: true

      - name: create tags
        if: ${{env.should_add_last_changes_to_master == 'true'}}
        run: |
          project_version=$(cat VERSION)
          tag_name="$project_version"
          release_message="Version $project_version"
          echo "tag_name=$tag_name" >> $GITHUB_ENV
          echo "release_message=$release_message" >> $GITHUB_ENV

      - name: create-push-tags
        if: ${{env.should_add_last_changes_to_master == 'true'}}
        id: "tag_create"
        uses: rickstaa/action-create-tag@v1
        with:
          github_token: ${{ secrets.TOKEN_CHANGELOG }}
          tag: ${{env.tag_name}}
          tag_exists_error: false
          message: ${{env.release_message}}

      - name: create-develop-branch
        uses: morbalint/git-merge-action@v1
        with:
          target: "develop"
          source: "main"
          token: ${{ secrets.TOKEN_CHANGELOG }}
          strategy_options: "ours"
